// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKP5YeqC-kXSOOiKlVOQA_IxNVQs16vuk',
    appId: '1:309212778157:web:7769e7f6130c8f1e5d4024',
    messagingSenderId: '309212778157',
    projectId: 'lautanrejeki-7a78f',
    authDomain: 'lautanrejeki-7a78f.firebaseapp.com',
    storageBucket: 'lautanrejeki-7a78f.firebasestorage.app',
    measurementId: 'G-5EF30CD6PK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9mDKIpHua6tU9kFesdwpY2i7JUHURXdk',
    appId: '1:309212778157:android:510f13d90f3cc0c55d4024',
    messagingSenderId: '309212778157',
    projectId: 'lautanrejeki-7a78f',
    storageBucket: 'lautanrejeki-7a78f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSsXKkEhh2hzayzE5ev0tB8rHxo_U8oUY',
    appId: '1:309212778157:ios:02f2c97fa3d523225d4024',
    messagingSenderId: '309212778157',
    projectId: 'lautanrejeki-7a78f',
    storageBucket: 'lautanrejeki-7a78f.firebasestorage.app',
    iosBundleId: 'com.example.lautanrejeki',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSsXKkEhh2hzayzE5ev0tB8rHxo_U8oUY',
    appId: '1:309212778157:ios:02f2c97fa3d523225d4024',
    messagingSenderId: '309212778157',
    projectId: 'lautanrejeki-7a78f',
    storageBucket: 'lautanrejeki-7a78f.firebasestorage.app',
    iosBundleId: 'com.example.lautanrejeki',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKP5YeqC-kXSOOiKlVOQA_IxNVQs16vuk',
    appId: '1:309212778157:web:139d2f447da241255d4024',
    messagingSenderId: '309212778157',
    projectId: 'lautanrejeki-7a78f',
    authDomain: 'lautanrejeki-7a78f.firebaseapp.com',
    storageBucket: 'lautanrejeki-7a78f.firebasestorage.app',
    measurementId: 'G-9JDBJ2WTQR',
  );
}
